//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadMagazine.Domain.Concrete.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int ClientId { get; set; }
    }
}
