//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadMagazine.Domain.Concrete.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int Id_Noticia { get; set; }
        public int Id_Channel { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Descripcion { get; set; }
        public string Contenido { get; set; }
        public string UrlImage { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
